CREATE TABLE BOARDS--데이터가 쌓이는 순서는 내가 결정할 수 없다
(
    BID     NUMBER(5)   PRIMARY KEY,
    BTITLE  VARCHAR2(100)   NOT NULL,
    PARENTID NUMBER(5)  NOT NULL
);

INSERT INTO BOARDS VALUES(1,'1-0',0);
INSERT INTO BOARDS VALUES(2,'2-0',0);
INSERT INTO BOARDS VALUES(3,'3-0',0);

SELECT * FROM BOARDS;

SELECT *
FROM BOARDS
START WITH PARENTID = 0
CONNECT BY PRIOR BID = PARENTID
ORDER SIBLINGS BY BID DESC
;
--COMMIT;

--1.첫번째 새글(1-0)에 첫번째 답글
INSERT INTO BOARDS VALUES(4,'1-0-1',1);

--2.두번째 새글(2-0)에 첫번째 답글
INSERT INTO BOARDS VALUES(5,'2-0-1',2);

--3.첫번째 새글(1-0)에 첫번째 답글의 첫번째 답글
INSERT INTO BOARDS VALUES(6,'1-0-1-1',4);

--4.첫번재 새글(1-0)에 두번째 답글
INSERT INTO BOARDS VALUES(7,'1-0-2',1);

SELECT BID, LPAD(BTITLE, LENGTH(BTITLE) + LEVEL,' '), PARENTID, LEVEL
FROM BOARDS
START WITH PARENTID = 0
CONNECT BY PRIOR BID = PARENTID
ORDER SIBLINGS BY BID DESC
;--할 수 있다는 것만 알고 있고 신경 많이 쓰지 말긔,,,




