
--TRUNC - TRUNCATE 함수
--ROUND

--수학적
SELECT ROUND(13.577,2) FROM DUAL;
SELECT TRUNC(13.577,2) FROM DUAL; -- ROUND는 반올림하는데 TRUNC는 버림한다(수학적으론 버림인데 날짜에서도 날려주기 때문에 무조건 버림인건아님)
SELECT TRUNC(13.577,-2) FROM DUAL;
SELECT TRUNC(16.577,0) FROM DUAL;
SELECT TRUNC(208.67,-2) FROM DUAL;

--날짜에서 TRUNC를 가끔 쓴다.

SELECT TO_CHAR(TRUNC(SYSDATE),'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

CREATE TABLE IMS
(
    DATE1       DATE        NOT NULL,
    DATE2       DATE        NOT NULL
);

INSERT INTO IMS VALUES(
    TO_DATE('2021-04-14 11:14:33','YYYY-MM-DD HH:MI:SS'),
    TO_DATE('2021-01-19 11:14:33','YYYY-MM-DD HH:MI:SS')
);

--COMMIT;
SELECT DATE1 - DATE2 FROM IMS;
SELECT TRUNC(DATE1), TRUNC(DATE2), TRUNC(DATE1)-TRUNC(DATE2) FROM IMS;
--TO_DATE를 하면 시분초가 생기는데 TRUNC를 하면 시분초가 다 날라가서 계산이 가능해진다

SELECT TO_CHAR(TRUNC(SYSDATE, 'YEAR'), 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
SELECT TO_CHAR(TRUNC(SYSDATE, 'MONTH'), 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
SELECT TO_CHAR(TRUNC(SYSDATE, 'DAY'), 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
-- DAY라고 적으면 현재날짜의 제일 최근 (앞전)일요일 날짜를 리턴한다
SELECT TO_CHAR(TRUNC(SYSDATE, 'DD'), 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
SELECT TO_CHAR(TRUNC(SYSDATE, 'YYYY'), 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

--이번달 1일부터 마지막날짜까지를 표시
SELECT  TO_DATE(TRUNC(SYSDATE,'MONTH')), (LEVEL-1),
        TO_DATE(TRUNC(SYSDATE,'MONTH'))+(LEVEL-1)
FROM  DUAL
CONNECT BY LEVEL <= TO_NUMBER(TO_CHAR(LAST_DAY(SYSDATE),'DD'))
;
------------------변수를 넣어서 활용 
SELECT  TO_DATE(TRUNC(TO_DATE(:INDATE),'MONTH')), (LEVEL-1),
        TO_DATE(TRUNC(TO_DATE(:INDATE),'MONTH'))+(LEVEL-1)
FROM  DUAL
CONNECT BY LEVEL <= TO_NUMBER(TO_CHAR(LAST_DAY(TO_DATE(:INDATE)),'DD'))
;

SELECT MOD(12,7) FROM DUAL; -- 나머지 함수
SELECT POWER(2,64) FROM DUAL; -- 제곱
SELECT ABS(-123) FROM DUAL; --절대값

