--문자열 함수들

--1. CONCAT --문자열을 합치는 함수

SELECT CONCAT('AAAA','BBBB') FROM DUAL;
SELECT PRO_COMPANY || '' || PRO_NAME FROM PRODUCTS_TBL;
SELECT CONCAT(PRO_COMPANY || '', PRO_NAME) FROM PRODUCTS_TBL;

--2. INITCAP --첫글자만 대문자로 바꾸고 나머지 문자는 전부 소문자로 바꾼다.
SELECT INITCAP('AAAAAAA') FROM DUAL;
SELECT INITCAP('aaaaaaa') FROM DUAL;
SELECT INITCAP('BbBbBbB') FROM DUAL;
SELECT INITCAP('tHiS IS a bOOk') FROM DUAL; -- 문법에 맞게 대소문자 바꿔준다.

--3. UPPER
SELECT UPPER('aaaaaa') FROM DUAL;
SELECT UPPER('AAAAAA') FROM DUAL;
SELECT UPPER('aaAAaaNNnn') FROM DUAL;
SELECT UPPER('tHiS IS a bOOk') FROM DUAL;

--4. LOWER 전체영문을 전부 다 소문자로 바꾼다.
SELECT LOWER('aaaa') FROM DUAL;
SELECT LOWER('AAAA') FROM DUAL;
SELECT LOWER('aaaa') FROM DUAL;
SELECT LOWER('tHiS IS a bOOk') FROM DUAL;

--*5. LPAD 많이 쓴다 중요. 문자열에 특정문자를 왼쪽에다 추가
SELECT LPAD('ABCDEF', 8, '@') FROM DUAL;
--ABCDEF는 6자리인데 숫자를 8을 줬으니 앞에 공간을 8-6=2 해서 2칸 공간을 주고 @를 넣는 것
--공백을 넣어줄 때 자주 쓴다
SELECT LPAD('ABCDEF', 9, ' ') FROM DUAL;
SELECT TO_CHAR(12, 'FM0000') FROM DUAL;
SELECT LPAD('12',4,'0') FROM DUAL;

--6. RPAD 특정문자를 오른쪽에다 추가
SELECT RPAD('ABCDEF', 8, '@') FROM DUAL;

--7. LTRIM 왼쪽 공백제거
SELECT LTRIM('    123456') FROM DUAL;
SELECT LTRIM('AAACCCBBBDDD','A') FROM DUAL;
--중간에 들어있는 문자는 의미 없음.
SELECT LTRIM('AAACCCBBBDDD','C') FROM DUAL;
-------------------------------------------
SELECT LTRIM('홍길동','홍') FROM DUAL;

--8. RTRIM 오른쪽 공백제거
SELECT RTRIM('123456    ') FROM DUAL;
SELECT RTRIM('AAACCCBBBDDD','A') FROM DUAL;
--중간에 들어있는 문자는 의미 없음.
SELECT RTRIM('AAACCCBBBDDD','D') FROM DUAL;
-------------------------------------------
SELECT RTRIM('홍길동','동') FROM DUAL;

--9. REPLACE 특정문자를 대체하는 함수
SELECT REPLACE('ABCD@@DFF' ,'@', '-') FROM DUAL; 
SELECT REPLACE('ABCD@@DFF' ,'@', '%%%') FROM DUAL; 
SELECT REPLACE('ABCD@@DFF' ,'@@', '%') FROM DUAL; 
SELECT REPLACE('ABCD@@DFF' ,'@@', '-') FROM DUAL; 
SELECT REPLACE('ABCD@@DFF' ,'@@', '  ') FROM DUAL; 
SELECT REPLACE('ABCD@@DFF' ,'@@', ' ') FROM DUAL; 
SELECT REPLACE('홍길동' ,'길', '상') FROM DUAL; 

--10. SUBSTR
SELECT SUBSTR('123456789' ,2, 5) FROM DUAL;
SELECT SUBSTR('123456789' ,4) FROM DUAL;
SELECT SUBSTR('123456789' ,-3) FROM DUAL;
SELECT SUBSTR('123456789' ,-7) FROM DUAL;
SELECT SUBSTR('123456789' ,-7,3) FROM DUAL;

--11. LENGTH // LENGTHB --특정문자열의 길이 // BYTE의 수
SELECT LENGTH(' 123456789 ') FROM DUAL;
SELECT LENGTH('123456789') FROM DUAL;
SELECT LENGTH('홍길동') FROM DUAL;

SELECT LENGTHB(' 123456789 ') FROM DUAL;
SELECT LENGTHB('123456789') FROM DUAL;
SELECT LENGTHB('홍길동') FROM DUAL;
SELECT LENGTHB('홍길동A가4') FROM DUAL;

--12. INSTR 자바스크립트에서 INDEXOF -- 특정문자열에 특정문자가 포함되어 있는지를 확인
SELECT 'ABCD@VCE@DEF@DDF' FROM DUAL;
SELECT INSTR('ABCD@VCE@DEF@DDF','@') FROM DUAL;
--맨앞에서부터 몇번째에 있는지 찾아준다

SELECT INSTR('ABCD@VCE@DEF@DDF','@',-1) FROM DUAL;
--뒤에서 찾는다(찾아서 세는건 뒤에서부터 셈)

--13. TRIM 양쪽 공백을 다 제거
SELECT TRIM(' SDDFSE ') FROM DUAL;

SELECT LTRIM(LTRIM(W_ID,'W'),'0') FROM BUY_TBL;

SELECT LTRIM(LTRIM(W_ID,'W'),'0') FROM BUY_TBL;

SELECT TO_NUMBER(SUBSTR(PRO_ID,2)) FROM BUY_TBL;
SELECT LTRIM(LTRIM(PRO_ID,'P'), '0') FROM BUY_TBL;

















