--회원별 구매금액
--회원, 월별기간

SELECT * FROM CUSTOMER_TBL;
SELECT * FROM SALES_TBL;

SELECT T1.C_ID, T1.C_NAME, SUM(T2.S_PRICE * T2.S_QTY) AS TLTPRICE 
FROM CUSTOMER_TBL T1, SALES_TBL T2
WHERE T1.C_ID = T2.C_ID(+)
GROUP BY T1.C_ID, T1.C_NAME
--그룹바이는 데이터를 뽑아놓고 거는게 좋다
;

SELECT C_ID, C_NAME, SUM(S_PRICE * S_QTY) FROM
(
SELECT T1.C_ID, T1.C_NAME, T2.S_PRICE , T2.S_QTY, TO_CHAR(T2.S_OUTDATE, 'YYYYMM') AS S_TLTPRICE 
FROM CUSTOMER_TBL T1, SALES_TBL T2
WHERE T1.C_ID = T2.C_ID(+)
AND T1.C_ID = 'C00001'
AND TO_CHAR(T2.S_OUTDATE, 'YYYYMM') >= '202102' AND TO_CHAR(T2.S_OUTDATE, 'YYYYMM') <= '202104'
)
GROUP BY C_ID,C_NAME
;
